version: '3'
services:
  # The Application
  mars-apache:
    build: ./app
    container_name: dev-${DOMAIN_NAME}-apache
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html/${DOMAIN_NAME}
      - ./web/apache/${ENV_FOLDER}/${ENV_FOLDER}.conf:/etc/apache2/sites-enabled/${DOMAIN}.conf
      - ./app/config/config.ini:/usr/local/etc/php/conf.d/config.ini
      - ./web/apache/${ENV_FOLDER}/:/etc/apache2/ssl/
    external_links:
      - mars-mysql-8.0
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      DOMAIN: ${DOMAIN}
      ENV_FOLDER: ${ENV_FOLDER}
      INSECURE_PORT: ${INSECURE_PORT}
      SECURE_PORT: ${SECURE_PORT}
      PROJECT_FOLDER: ${PROJECT_FOLDER}
    ports:
      - ${INSECURE_PORT}:80
      - ${SECURE_PORT}:443
    restart: on-failure

  mars-mysql-8.0:
    image: mysql:8.0
    command: --authentication_policy=mysql_native_password
    cap_add:
      - SYS_NICE
    container_name: mars-mysql-8.0
    volumes:
      - docker-mysql:/var/lib/mysql-8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=hWyns624AxhvWkZs"
      - "MYSQL_ROOT_HOST=%"
    ports:
      - ${MYSQL_PORT}:3306
    restart: on-failure


volumes:
  docker-mysql:

networks:
  default:
    name: trustiu-services
